name: Lint and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "gofmt found formatting issues"
            gofmt -s -d .
            exit 1
          fi

      - name: Test
        run: go test -v ./...
