name: Lint and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths: ["**.go"]

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"

      - name: Download dependencies
        run: go mod download

      - name: Lint with gofmt
        run: gofmt -s -l . | tee /dev/stderr | wc -l | xargs test 0 -eq

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          skip-cache: true

      - name: Test
        run: go test -v ./...
